#!/bin/sh

build() {
	source /etc/archlogo.conf
	add_file /etc/archlogo.conf
	add_file "/usr/share/archlogo/${ARCHLOGO}"
	if command -v add_systemd_unit >/dev/null; then
		add_systemd_unit "archlogo.service"
		add_symlink "/usr/lib/systemd/system/sysinit.target.wants/archlogo.service" "../archlogo.service"
	else
		add_runscript
	fi
}

help() {
	echo "This hook adds an Arch Linux logo to the boot process."
}
