#!/bin/sh

build() {
	source /etc/archlogo.conf
	add_file /etc/archlogo.conf
	add_file "/usr/share/archlogo/${ARCHLOGO}"
	add_systemd_unit archlogo.service
	add_symlink "/usr/lib/systemd/system/sysinit.target.wants/archlogo.service" "../archlogo.service"
}

help() {
	echo "This hook adds an Arch Linux logo to the boot process."
}
